
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `cf`=list(
        `type`="book", 
        `author`="Chernik, M. R., & Friis, R. H.", 
        `year`=2003, 
        `title`="Introductory biostatistics for the health sciences: Modern applications including bootstrap", 
        `publisher`="Wiley-Interscience. https://doi.org/10.1002/0471458716", 
        `url`="https://doi.org/10.1002/0471458716"), 
    `coin`=list(
        `type`="software", 
        `author`="Hothorn, T. & Hornik, K., & van de Wiel, M. A., & Zeileis, A.", 
        `year`=2006, 
        `title`="Implementing a class of permutation tests: The coin package", 
        `publisher`="[R package]. Retrieved from https://cran.r-project.org/package=coin", 
        `url`="https://cran.r-project.org/package=coin"), 
    `pratt`=list(
        `type`="article", 
        `author`="Pratt, J. W.", 
        `year`=1959, 
        `title`="Remarks on zeros and ties in the Wilcoxon signed rank procedures", 
        `publisher`="Journal of the American Statistical Association. https://doi10.1080/01621459.1959.10501526", 
        `url`="https://doi10.1080/01621459.1959.10501526"), 
    `wilcox`=list(
        `type`="book", 
        `author`="Wilcoxon, F.", 
        `year`=1949, 
        `title`="Some rapid approximate statistical procedures", 
        `publisher`="Cyanamid Company"))
