
# This file is automatically generated, you probably don't want to edit this

signtestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "signtestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            samp1 = NULL,
            samp2 = NULL,
            alternative = "two.sided", ...) {

            super$initialize(
                package="nonpara",
                name="signtest",
                requiresData=TRUE,
                ...)

            private$..samp1 <- jmvcore::OptionVariable$new(
                "samp1",
                samp1)
            private$..samp2 <- jmvcore::OptionVariable$new(
                "samp2",
                samp2)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "two.sided",
                    "greater",
                    "less"),
                default="two.sided")

            self$.addOption(private$..samp1)
            self$.addOption(private$..samp2)
            self$.addOption(private$..alternative)
        }),
    active = list(
        samp1 = function() private$..samp1$value,
        samp2 = function() private$..samp2$value,
        alternative = function() private$..alternative$value),
    private = list(
        ..samp1 = NA,
        ..samp2 = NA,
        ..alternative = NA)
)

signtestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "signtestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        table = function() private$.items[["table"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sign Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="text"))
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="Exact Sign Test",
                rows=1,
                columns=list(
                    list(
                        `name`="s1", 
                        `title`="Sample One", 
                        `type`="text"),
                    list(
                        `name`="alt", 
                        `title`="Alternative", 
                        `type`="text"),
                    list(
                        `name`="s2", 
                        `title`="Sample Two", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p-Value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

signtestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "signtestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nonpara",
                name = "signtest",
                version = c(1,0,0),
                options = options,
                results = signtestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Sign Test
#'
#' 
#' @param data .
#' @param samp1 .
#' @param samp2 .
#' @param alternative .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
signtest <- function(
    data,
    samp1,
    samp2,
    alternative = "two.sided") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("signtest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(samp1)) samp1 <- jmvcore::resolveQuo(jmvcore::enquo(samp1))
    if ( ! missing(samp2)) samp2 <- jmvcore::resolveQuo(jmvcore::enquo(samp2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(samp1), samp1, NULL),
            `if`( ! missing(samp2), samp2, NULL))


    options <- signtestOptions$new(
        samp1 = samp1,
        samp2 = samp2,
        alternative = alternative)

    analysis <- signtestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

