
# This file is automatically generated, you probably don't want to edit this

wilcoxRanksumOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wilcoxRanksumOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            exact = TRUE,
            approximate = FALSE,
            asymptotic = FALSE,
            cc = FALSE,
            alternative = "two.sided", ...) {

            super$initialize(
                package="nonpara",
                name="wilcoxRanksum",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..exact <- jmvcore::OptionBool$new(
                "exact",
                exact,
                default=TRUE)
            private$..approximate <- jmvcore::OptionBool$new(
                "approximate",
                approximate,
                default=FALSE)
            private$..asymptotic <- jmvcore::OptionBool$new(
                "asymptotic",
                asymptotic,
                default=FALSE)
            private$..cc <- jmvcore::OptionBool$new(
                "cc",
                cc,
                default=FALSE)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "less",
                    "two.sided",
                    "greater"),
                default="two.sided")

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..exact)
            self$.addOption(private$..approximate)
            self$.addOption(private$..asymptotic)
            self$.addOption(private$..cc)
            self$.addOption(private$..alternative)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        exact = function() private$..exact$value,
        approximate = function() private$..approximate$value,
        asymptotic = function() private$..asymptotic$value,
        cc = function() private$..cc$value,
        alternative = function() private$..alternative$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..exact = NA,
        ..approximate = NA,
        ..asymptotic = NA,
        ..cc = NA,
        ..alternative = NA)
)

wilcoxRanksumResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wilcoxRanksumResults",
    inherit = jmvcore::Group,
    active = list(
        wrs = function() private$.items[["wrs"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Wilcoxon Rank-Sum Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="wrs",
                title="Wilcoxon Rank-Sum Test",
                rows=1,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="type[ex]", 
                        `title`="Type", 
                        `type`="text", 
                        `visible`="(exact)"),
                    list(
                        `name`="stat[ex]", 
                        `title`="Statistic", 
                        `type`="text", 
                        `visible`="(exact)"),
                    list(
                        `name`="p[ex]", 
                        `title`="<i>p</i>-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(exact)"),
                    list(
                        `name`="type[app]", 
                        `title`="Type", 
                        `type`="text", 
                        `visible`="(approximate)"),
                    list(
                        `name`="stat[app]", 
                        `title`="Statistic", 
                        `type`="text", 
                        `visible`="(approximate)"),
                    list(
                        `name`="p[app]", 
                        `title`="<i>p</i>-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(approximate)"),
                    list(
                        `name`="type[asy]", 
                        `title`="Type", 
                        `type`="text", 
                        `visible`="(asymptotic)"),
                    list(
                        `name`="stat[asy]", 
                        `title`="Statistic", 
                        `type`="text", 
                        `visible`="(asymptotic)"),
                    list(
                        `name`="p[asy]", 
                        `title`="<i>p</i>-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(asymptotic)"),
                    list(
                        `name`="type[cc]", 
                        `title`="Type", 
                        `type`="text", 
                        `visible`="(cc)"),
                    list(
                        `name`="stat[cc]", 
                        `title`="Statistic", 
                        `type`="text", 
                        `visible`="(cc)"),
                    list(
                        `name`="p[cc]", 
                        `title`="<i>p</i>-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(cc)"))))}))

wilcoxRanksumBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wilcoxRanksumBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nonpara",
                name = "wilcoxRanksum",
                version = c(0,0,0),
                options = options,
                results = wilcoxRanksumResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Wilcoxon Rank-Sum Test
#'
#' 
#' @param data the data as a data frame
#' @param dep Dependent variable. Does not neet to be specified when using a
#'   formula.
#' @param group Grouping variable, must have two levels. Does not neet to be
#'   specified when using a formula.
#' @param exact .
#' @param approximate .
#' @param asymptotic .
#' @param cc .
#' @param alternative .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$wrs} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$wrs$asDF}
#'
#' \code{as.data.frame(results$wrs)}
#'
#' @export
wilcoxRanksum <- function(
    data,
    dep,
    group,
    exact = TRUE,
    approximate = FALSE,
    asymptotic = FALSE,
    cc = FALSE,
    alternative = "two.sided") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("wilcoxRanksum requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- wilcoxRanksumOptions$new(
        dep = dep,
        group = group,
        exact = exact,
        approximate = approximate,
        asymptotic = asymptotic,
        cc = cc,
        alternative = alternative)

    analysis <- wilcoxRanksumClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

