
# This file is automatically generated, you probably don't want to edit this

wilcoxRanksumOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wilcoxRanksumOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            exact = TRUE,
            approximate = FALSE,
            nsamples = 10000,
            asymptotic = FALSE,
            cc = FALSE,
            alternative = "two.sided",
            rs1 = FALSE,
            u = FALSE,
            descriptives = FALSE,
            plot = FALSE,
            observed = FALSE, ...) {

            super$initialize(
                package="nonpara",
                name="wilcoxRanksum",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..exact <- jmvcore::OptionBool$new(
                "exact",
                exact,
                default=TRUE)
            private$..approximate <- jmvcore::OptionBool$new(
                "approximate",
                approximate,
                default=FALSE)
            private$..nsamples <- jmvcore::OptionInteger$new(
                "nsamples",
                nsamples,
                default=10000)
            private$..asymptotic <- jmvcore::OptionBool$new(
                "asymptotic",
                asymptotic,
                default=FALSE)
            private$..cc <- jmvcore::OptionBool$new(
                "cc",
                cc,
                default=FALSE)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "less",
                    "two.sided",
                    "greater"),
                default="two.sided")
            private$..rs1 <- jmvcore::OptionBool$new(
                "rs1",
                rs1,
                default=FALSE)
            private$..u <- jmvcore::OptionBool$new(
                "u",
                u,
                default=FALSE)
            private$..descriptives <- jmvcore::OptionBool$new(
                "descriptives",
                descriptives,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..observed <- jmvcore::OptionBool$new(
                "observed",
                observed,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..exact)
            self$.addOption(private$..approximate)
            self$.addOption(private$..nsamples)
            self$.addOption(private$..asymptotic)
            self$.addOption(private$..cc)
            self$.addOption(private$..alternative)
            self$.addOption(private$..rs1)
            self$.addOption(private$..u)
            self$.addOption(private$..descriptives)
            self$.addOption(private$..plot)
            self$.addOption(private$..observed)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        exact = function() private$..exact$value,
        approximate = function() private$..approximate$value,
        nsamples = function() private$..nsamples$value,
        asymptotic = function() private$..asymptotic$value,
        cc = function() private$..cc$value,
        alternative = function() private$..alternative$value,
        rs1 = function() private$..rs1$value,
        u = function() private$..u$value,
        descriptives = function() private$..descriptives$value,
        plot = function() private$..plot$value,
        observed = function() private$..observed$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..exact = NA,
        ..approximate = NA,
        ..nsamples = NA,
        ..asymptotic = NA,
        ..cc = NA,
        ..alternative = NA,
        ..rs1 = NA,
        ..u = NA,
        ..descriptives = NA,
        ..plot = NA,
        ..observed = NA)
)

wilcoxRanksumResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wilcoxRanksumResults",
    inherit = jmvcore::Group,
    active = list(
        wrs = function() private$.items[["wrs"]],
        desc = function() private$.items[["desc"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Wilcoxon Rank-Sum Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="wrs",
                title="Wilcoxon Rank-Sum Test",
                refs=list(
                    "coin"),
                clearWith=list(
                    "data",
                    "dep",
                    "group"),
                rows=1,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="type[exact]", 
                        `title`="Type", 
                        `type`="text", 
                        `visible`="(exact)"),
                    list(
                        `name`="stat[exact]", 
                        `title`="<i>z</i>-Value", 
                        `type`="text", 
                        `visible`="(exact)"),
                    list(
                        `name`="rs1[exact]", 
                        `title`="<i>RS</i><sub>1</sub>", 
                        `type`="number", 
                        `visible`="(exact && rs1)"),
                    list(
                        `name`="u[exact]", 
                        `title`="<i>U</i>", 
                        `type`="number", 
                        `visible`="(exact && u)"),
                    list(
                        `name`="p[exact]", 
                        `title`="<i>p</i>-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(exact)"),
                    list(
                        `name`="type[approximate]", 
                        `title`="Type", 
                        `type`="text", 
                        `visible`="(approximate)"),
                    list(
                        `name`="stat[approximate]", 
                        `title`="<i>z</i>-Value", 
                        `type`="text", 
                        `visible`="(approximate)"),
                    list(
                        `name`="rs1[approximate]", 
                        `title`="<i>RS</i><sub>1</sub>", 
                        `type`="number", 
                        `visible`="(approximate && rs1)"),
                    list(
                        `name`="u[approximate]", 
                        `title`="<i>U</i>", 
                        `type`="number", 
                        `visible`="(approximate && u)"),
                    list(
                        `name`="p[approximate]", 
                        `title`="<i>p</i>-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(approximate)"),
                    list(
                        `name`="type[asymptotic]", 
                        `title`="Type", 
                        `type`="text", 
                        `visible`="(asymptotic)"),
                    list(
                        `name`="stat[asymptotic]", 
                        `title`="<i>z</i>-Value", 
                        `type`="text", 
                        `visible`="(asymptotic)"),
                    list(
                        `name`="rs1[asymptotic]", 
                        `title`="<i>RS</i><sub>1</sub>", 
                        `type`="number", 
                        `visible`="(asymptotic && rs1)"),
                    list(
                        `name`="u[asymptotic]", 
                        `title`="<i>U</i>", 
                        `type`="number", 
                        `visible`="(asymptotic && u)"),
                    list(
                        `name`="p[asymptotic]", 
                        `title`="<i>p</i>-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(asymptotic)"),
                    list(
                        `name`="type[cc]", 
                        `title`="Type", 
                        `type`="text", 
                        `visible`="(cc && asymptotic)"),
                    list(
                        `name`="stat[cc]", 
                        `title`="<i>z</i>-Value", 
                        `type`="text", 
                        `visible`="(cc && asymptotic)", 
                        `refs`=list(
                            "cf")),
                    list(
                        `name`="rs1[cc]", 
                        `title`="<i>RS</i><sub>1</sub>", 
                        `type`="number", 
                        `visible`="(cc && asymptotic && rs1)"),
                    list(
                        `name`="u[cc]", 
                        `title`="<i>U</i>", 
                        `type`="number", 
                        `visible`="(cc && asymptotic && u)"),
                    list(
                        `name`="p[cc]", 
                        `title`="<i>p</i>-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(cc && asymptotic)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptive Statistics",
                visible="(descriptives)",
                clearWith=list(
                    "group",
                    "dep",
                    "data"),
                rows=1,
                columns=list(
                    list(
                        `name`="dep", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="group[1]", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="num[1]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="median[1]", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="rankmean[1]", 
                        `title`="Rankmean", 
                        `type`="number"),
                    list(
                        `name`="group[2]", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="num[2]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="median[2]", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="rankmean[2]", 
                        `title`="Rankmean", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Descriptives Plot",
                width=400,
                height=300,
                visible="(plot)",
                renderFun=".descplot",
                clearWith=list(
                    "group",
                    "dep",
                    "data",
                    "observed")))}))

wilcoxRanksumBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wilcoxRanksumBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nonpara",
                name = "wilcoxRanksum",
                version = c(0,0,0),
                options = options,
                results = wilcoxRanksumResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Wilcoxon Rank-Sum Test
#'
#' 
#' @param data the data as a data frame
#' @param dep Dependent variable. Does not neet to be specified when using a
#'   formula.
#' @param group Grouping variable, must have two levels. Does not need to be
#'   specified when using a formula.
#' @param exact .
#' @param approximate .
#' @param nsamples .
#' @param asymptotic .
#' @param cc .
#' @param alternative .
#' @param rs1 .
#' @param u .
#' @param descriptives .
#' @param plot .
#' @param observed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$wrs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$wrs$asDF}
#'
#' \code{as.data.frame(results$wrs)}
#'
#' @export
wilcoxRanksum <- function(
    data,
    dep,
    group,
    exact = TRUE,
    approximate = FALSE,
    nsamples = 10000,
    asymptotic = FALSE,
    cc = FALSE,
    alternative = "two.sided",
    rs1 = FALSE,
    u = FALSE,
    descriptives = FALSE,
    plot = FALSE,
    observed = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("wilcoxRanksum requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- wilcoxRanksumOptions$new(
        dep = dep,
        group = group,
        exact = exact,
        approximate = approximate,
        nsamples = nsamples,
        asymptotic = asymptotic,
        cc = cc,
        alternative = alternative,
        rs1 = rs1,
        u = u,
        descriptives = descriptives,
        plot = plot,
        observed = observed)

    analysis <- wilcoxRanksumClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

