
# This file is automatically generated, you probably don't want to edit this

wrsTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wrsTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            dist = "exact",
            alternative = "two.sided", ...) {

            super$initialize(
                package="nonpara",
                name="wrsTest",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..dist <- jmvcore::OptionList$new(
                "dist",
                dist,
                options=list(
                    "exact",
                    "approximate",
                    "asymptoticCC",
                    "asymptotic"),
                default="exact")
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "less",
                    "two.sided",
                    "greater"),
                default="two.sided")

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..dist)
            self$.addOption(private$..alternative)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        dist = function() private$..dist$value,
        alternative = function() private$..alternative$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..dist = NA,
        ..alternative = NA)
)

wrsTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wrsTestResults",
    inherit = jmvcore::Group,
    active = list(
        wrs = function() private$.items[["wrs"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="wrsTest")
            self$add(jmvcore::Table$new(
                options=options,
                name="wrs",
                title="Wilcoxon Rank-Sum Test",
                rows=1,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="p-Value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

wrsTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wrsTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nonpara",
                name = "wrsTest",
                version = c(1,0,0),
                options = options,
                results = wrsTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' wrsTest
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param dist .
#' @param alternative .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$wrs} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$wrs$asDF}
#'
#' \code{as.data.frame(results$wrs)}
#'
#' @export
wrsTest <- function(
    data,
    dep,
    group,
    dist = "exact",
    alternative = "two.sided") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("wrsTest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- wrsTestOptions$new(
        dep = dep,
        group = group,
        dist = dist,
        alternative = alternative)

    analysis <- wrsTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

